// Auto-generated route configuration
// This file is automatically generated by the route-generator plugin
// Do not edit manually - your changes will be overwritten

import Route0 from '../contents/index.mdx'
import Route1 from '../contents/deployment/index.mdx'
import Route2 from '../contents/deployment/cloudflare-pages.mdx'
import Route3 from '../contents/deployment/docker.mdx'
import Route4 from '../contents/deployment/github-action.mdx'
import Route5 from '../contents/deployment/github-pages.mdx'
import Route6 from '../contents/deployment/Netlify.mdx'
import Route7 from '../contents/deployment/Vercel.mdx'
import Route8 from '../contents/development/index.mdx'
import Route9 from '../contents/storage/index.mdx'
import Route10 from '../contents/usedb/postgresql.mdx'

export interface RouteConfig {
  path: string
  component: React.ComponentType
  title: string
  meta: Record<string, unknown>
}

export const routes: RouteConfig[] = [
  {
    path: '/',
    component: Route0,
    title: '概述',
    meta: {
        "title": "概述",
        "createdAt": "2025-07-20T22:35:03+08:00",
        "lastModified": "2025-09-14T19:54:27+08:00"
    }
  },
  {
    path: '/deployment',
    component: Route1,
    title: '部署指南',
    meta: {
        "title": "部署指南",
        "description": "关于在生产环境中部署 Afilmory 的指南",
        "createdAt": "2025-07-20T22:35:03+08:00",
        "lastModified": "2025-09-17T14:55:42+08:00"
    }
  },
  {
    path: '/deployment/cloudflare-pages',
    component: Route2,
    title: 'Cloudflare Pages 🚧',
    meta: {
        "title": "Cloudflare Pages 🚧",
        "description": "通过 Cloudflare Pages 部署 Afilmory 的指南",
        "createdAt": "2025-07-20T22:35:03+08:00",
        "lastModified": "2025-09-17T14:55:42+08:00"
    }
  },
  {
    path: '/deployment/docker',
    component: Route3,
    title: 'Docker',
    meta: {
        "title": "Docker",
        "description": "通过 Docker 部署 Afilmory 的指南",
        "createdAt": "2025-07-20T22:35:03+08:00",
        "lastModified": "2025-09-14T19:54:27+08:00"
    }
  },
  {
    path: '/deployment/github-action',
    component: Route4,
    title: 'Github Action 🚧',
    meta: {
        "title": "Github Action 🚧",
        "description": "通过 Github Action 部署 Afilmory 的指南",
        "createdAt": "2025-07-20T22:35:03+08:00",
        "lastModified": "2025-09-17T14:55:42+08:00"
    }
  },
  {
    path: '/deployment/github-pages',
    component: Route5,
    title: 'Github Pages 🚧',
    meta: {
        "title": "Github Pages 🚧",
        "description": "通过 Github Pages 部署 Afilmory 的指南",
        "createdAt": "2025-07-20T22:35:03+08:00",
        "lastModified": "2025-09-17T14:55:42+08:00"
    }
  },
  {
    path: '/deployment/Netlify',
    component: Route6,
    title: 'Netlify',
    meta: {
        "title": "Netlify",
        "description": "在 Netlify.app 上部署 Afilmory 的指南。",
        "createdAt": "2025-09-16T09:22:17+08:00",
        "lastModified": "2025-09-17T14:55:42+08:00"
    }
  },
  {
    path: '/deployment/Vercel',
    component: Route7,
    title: 'Vercel',
    meta: {
        "title": "Vercel",
        "description": "在 Vercel 上部署 Afilmory 的指南。",
        "createdAt": "2025-09-15T20:35:03+08:00",
        "lastModified": "2025-09-17T14:55:42+08:00"
    }
  },
  {
    path: '/development',
    component: Route8,
    title: '本地开发指南',
    meta: {
        "title": "本地开发指南",
        "description": "Afilmory本地开发指南",
        "createdAt": "2025-09-17T21:26:08+08:00",
        "lastModified": "2025-09-17T14:55:42+08:00"
    }
  },
  {
    path: '/storage',
    component: Route9,
    title: '存储提供商',
    meta: {
        "title": "存储提供商",
        "description": "Afilmory 可以与多种存储提供商配合使用，包括 S3、Git 和本地文件系统",
        "createdAt": "2025-08-12T15:09:08+08:00",
        "lastModified": "2025-09-14T19:54:27+08:00"
    }
  },
  {
    path: '/usedb/postgresql',
    component: Route10,
    title: '数据库申请',
    meta: {
        "title": "数据库申请",
        "description": "Afilmory点赞和浏览量需要数据库的支持，此文档将说明如何申请免费的PostgreSQL用于Afilmory",
        "createdAt": "2025-09-17T14:47:44+08:00",
        "lastModified": "2025-09-17T14:55:42+08:00"
    }
  }
]

export default routes
