// This file is automatically generated by the toc-extractor plugin
// Do not edit manually

export interface TocItem {
  id: string
  level: number
  text: string
  children?: TocItem[]
}

export interface FileToc {
  file: string
  path: string
  title: string
  toc: TocItem[]
}

export const tocData: FileToc[] = [
  {
    "file": "index.mdx",
    "path": "/",
    "title": "概述",
    "toc": [
      {
        "id": "heading-概述",
        "level": 1,
        "text": "概述",
        "children": [
          {
            "id": "heading-🌟-特性",
            "level": 2,
            "text": "🌟 特性",
            "children": [
              {
                "id": "heading-核心功能",
                "level": 3,
                "text": "核心功能",
                "children": []
              },
              {
                "id": "heading-图像处理",
                "level": 3,
                "text": "图像处理",
                "children": []
              },
              {
                "id": "heading-高级特性",
                "level": 3,
                "text": "高级特性",
                "children": []
              }
            ]
          },
          {
            "id": "heading-🏗️-技术架构",
            "level": 2,
            "text": "🏗️ 技术架构",
            "children": [
              {
                "id": "heading-前端技术栈",
                "level": 3,
                "text": "前端技术栈",
                "children": []
              },
              {
                "id": "heading-构建系统",
                "level": 3,
                "text": "构建系统",
                "children": []
              },
              {
                "id": "heading-存储架构",
                "level": 3,
                "text": "存储架构",
                "children": []
              }
            ]
          },
          {
            "id": "heading-📄-许可证",
            "level": 2,
            "text": "📄 许可证",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "file": "deployment/index.mdx",
    "path": "/deployment",
    "title": "部署指南",
    "toc": [
      {
        "id": "heading-部署指南",
        "level": 1,
        "text": "部署指南",
        "children": []
      }
    ]
  },
  {
    "file": "deployment/cloudflare-pages.mdx",
    "path": "/deployment/cloudflare-pages",
    "title": "Cloudflare Pages 🚧",
    "toc": [
      {
        "id": "heading-Cloudflare-Pages-部署",
        "level": 1,
        "text": "Cloudflare Pages 部署",
        "children": []
      }
    ]
  },
  {
    "file": "deployment/docker.mdx",
    "path": "/deployment/docker",
    "title": "Docker",
    "toc": [
      {
        "id": "heading-Docker-部署",
        "level": 1,
        "text": "Docker 部署",
        "children": [
          {
            "id": "heading-快速摘要",
            "level": 2,
            "text": "快速摘要",
            "children": [
              {
                "id": "heading-说明",
                "level": 3,
                "text": "说明",
                "children": []
              }
            ]
          },
          {
            "id": "heading-🚀-快速开始",
            "level": 2,
            "text": "🚀 快速开始",
            "children": [
              {
                "id": "heading-前提条件",
                "level": 3,
                "text": "前提条件",
                "children": []
              },
              {
                "id": "heading-1-配置文件",
                "level": 3,
                "text": "1. 配置文件",
                "children": []
              },
              {
                "id": "heading-2-Dockerfile-设置",
                "level": 3,
                "text": "2. Dockerfile 设置",
                "children": []
              },
              {
                "id": "heading-3-Docker-Compose-设置",
                "level": 3,
                "text": "3. Docker Compose 设置",
                "children": []
              },
              {
                "id": "heading-4-构建和运行",
                "level": 3,
                "text": "4. 构建和运行",
                "children": [
                  {
                    "id": "heading-选项-1：使用-Docker-Compose（推荐）",
                    "level": 4,
                    "text": "选项 1：使用 Docker Compose（推荐）",
                    "children": []
                  },
                  {
                    "id": "heading-选项-2：手动-Docker-构建",
                    "level": 4,
                    "text": "选项 2：手动 Docker 构建",
                    "children": []
                  }
                ]
              }
            ]
          },
          {
            "id": "heading-📋-配置详情",
            "level": 2,
            "text": "📋 配置详情",
            "children": [
              {
                "id": "heading-存储提供商",
                "level": 3,
                "text": "存储提供商",
                "children": []
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "file": "deployment/github-action.mdx",
    "path": "/deployment/github-action",
    "title": "Github Action 🚧",
    "toc": [
      {
        "id": "heading-Github-Action-部署",
        "level": 1,
        "text": "Github Action 部署",
        "children": []
      }
    ]
  },
  {
    "file": "deployment/github-pages.mdx",
    "path": "/deployment/github-pages",
    "title": "Github Pages 🚧",
    "toc": [
      {
        "id": "heading-Github-Pages-部署",
        "level": 1,
        "text": "Github Pages 部署",
        "children": []
      }
    ]
  },
  {
    "file": "deployment/Netlify.mdx",
    "path": "/deployment/Netlify",
    "title": "Netlify",
    "toc": [
      {
        "id": "heading-Netlify部署指南",
        "level": 1,
        "text": "Netlify部署指南",
        "children": [
          {
            "id": "heading-🍕-准备工作",
            "level": 2,
            "text": "🍕 准备工作",
            "children": []
          },
          {
            "id": "heading-🚀-快速开始",
            "level": 2,
            "text": "🚀 快速开始",
            "children": []
          },
          {
            "id": "heading-🎑-注册登录Netlify",
            "level": 2,
            "text": "🎑 注册登录Netlify",
            "children": [
              {
                "id": "heading-使用GitHub注册",
                "level": 3,
                "text": "使用GitHub注册",
                "children": []
              }
            ]
          },
          {
            "id": "heading-👏开始部署",
            "level": 2,
            "text": "👏开始部署",
            "children": [
              {
                "id": "heading-导入项目",
                "level": 3,
                "text": "导入项目",
                "children": []
              },
              {
                "id": "heading-部署设置",
                "level": 3,
                "text": "部署设置",
                "children": []
              }
            ]
          },
          {
            "id": "heading-🌏-域名配置",
            "level": 2,
            "text": "🌏 域名配置",
            "children": []
          },
          {
            "id": "heading-⁉️问题解决",
            "level": 2,
            "text": "⁉️问题解决",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "file": "deployment/Vercel.mdx",
    "path": "/deployment/Vercel",
    "title": "Vercel",
    "toc": [
      {
        "id": "heading-Vercel-部署指南",
        "level": 1,
        "text": "Vercel 部署指南",
        "children": [
          {
            "id": "heading-🍕-准备工作",
            "level": 2,
            "text": "🍕 准备工作",
            "children": []
          },
          {
            "id": "heading-🚀-快速开始",
            "level": 2,
            "text": "🚀 快速开始",
            "children": []
          },
          {
            "id": "heading-🎑-注册登录Vercel",
            "level": 2,
            "text": "🎑 注册登录Vercel",
            "children": []
          },
          {
            "id": "heading-🖊️部署项目",
            "level": 2,
            "text": "🖊️部署项目",
            "children": [
              {
                "id": "heading-导入GitHub项目",
                "level": 3,
                "text": "导入GitHub项目",
                "children": []
              },
              {
                "id": "heading-环境变量配置",
                "level": 3,
                "text": "环境变量配置",
                "children": []
              }
            ]
          },
          {
            "id": "heading-🌏-域名配置",
            "level": 2,
            "text": "🌏 域名配置",
            "children": []
          },
          {
            "id": "heading-🔘-快速部署",
            "level": 2,
            "text": "🔘 快速部署",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "file": "development/index.mdx",
    "path": "/development",
    "title": "本地开发指南",
    "toc": [
      {
        "id": "heading-本地开发指南",
        "level": 1,
        "text": "本地开发指南",
        "children": []
      }
    ]
  },
  {
    "file": "docs-site.mdx",
    "path": "/docs-site",
    "title": "文档站点",
    "toc": [
      {
        "id": "heading-Afilmory-文档站点",
        "level": 1,
        "text": "Afilmory 文档站点",
        "children": [
          {
            "id": "heading-功能特性",
            "level": 2,
            "text": "功能特性",
            "children": []
          },
          {
            "id": "heading-快速开始",
            "level": 2,
            "text": "快速开始",
            "children": [
              {
                "id": "heading-开发",
                "level": 3,
                "text": "开发",
                "children": []
              },
              {
                "id": "heading-构建",
                "level": 3,
                "text": "构建",
                "children": []
              },
              {
                "id": "heading-预览",
                "level": 3,
                "text": "预览",
                "children": []
              }
            ]
          },
          {
            "id": "heading-项目结构",
            "level": 2,
            "text": "项目结构",
            "children": []
          },
          {
            "id": "heading-编写文档",
            "level": 2,
            "text": "编写文档",
            "children": [
              {
                "id": "heading-基于文件的路由",
                "level": 3,
                "text": "基于文件的路由",
                "children": []
              },
              {
                "id": "heading-MDX-格式",
                "level": 3,
                "text": "MDX 格式",
                "children": []
              },
              {
                "id": "heading-前置元数据",
                "level": 3,
                "text": "前置元数据",
                "children": []
              }
            ]
          },
          {
            "id": "heading-开发指南",
            "level": 2,
            "text": "开发指南",
            "children": [
              {
                "id": "heading-添加新内容",
                "level": 3,
                "text": "添加新内容",
                "children": []
              },
              {
                "id": "heading-自定义组件",
                "level": 3,
                "text": "自定义组件",
                "children": []
              },
              {
                "id": "heading-样式",
                "level": 3,
                "text": "样式",
                "children": []
              },
              {
                "id": "heading-路由生成插件",
                "level": 3,
                "text": "路由生成插件",
                "children": []
              }
            ]
          },
          {
            "id": "heading-配置",
            "level": 2,
            "text": "配置",
            "children": [
              {
                "id": "heading-Vite-配置",
                "level": 3,
                "text": "Vite 配置",
                "children": []
              },
              {
                "id": "heading-支持的语言",
                "level": 3,
                "text": "支持的语言",
                "children": []
              }
            ]
          },
          {
            "id": "heading-部署",
            "level": 2,
            "text": "部署",
            "children": []
          },
          {
            "id": "heading-脚本参考",
            "level": 2,
            "text": "脚本参考",
            "children": []
          },
          {
            "id": "heading-贡献指南",
            "level": 2,
            "text": "贡献指南",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "file": "storage/index.mdx",
    "path": "/storage",
    "title": "存储提供商",
    "toc": [
      {
        "id": "heading-存储提供商",
        "level": 1,
        "text": "存储提供商",
        "children": [
          {
            "id": "heading-支持的提供商",
            "level": 2,
            "text": "支持的提供商",
            "children": [
              {
                "id": "heading-S3-兼容存储",
                "level": 3,
                "text": "S3 兼容存储",
                "children": []
              },
              {
                "id": "heading-GitHub-存储",
                "level": 3,
                "text": "GitHub 存储",
                "children": []
              },
              {
                "id": "heading-本地文件系统",
                "level": 3,
                "text": "本地文件系统",
                "children": []
              }
            ]
          },
          {
            "id": "heading-照片处理工作流",
            "level": 2,
            "text": "照片处理工作流",
            "children": [
              {
                "id": "heading-图像处理流水线",
                "level": 3,
                "text": "图像处理流水线",
                "children": []
              },
              {
                "id": "heading-存储组织",
                "level": 3,
                "text": "存储组织",
                "children": []
              },
              {
                "id": "heading-处理命令",
                "level": 3,
                "text": "处理命令",
                "children": []
              }
            ]
          },
          {
            "id": "heading-环境特定配置",
            "level": 2,
            "text": "环境特定配置",
            "children": [
              {
                "id": "heading-开发设置",
                "level": 3,
                "text": "开发设置",
                "children": []
              },
              {
                "id": "heading-生产设置",
                "level": 3,
                "text": "生产设置",
                "children": []
              }
            ]
          },
          {
            "id": "heading-API-限制",
            "level": 2,
            "text": "API 限制",
            "children": [
              {
                "id": "heading-GitHub-存储限制",
                "level": 3,
                "text": "GitHub 存储限制",
                "children": []
              },
              {
                "id": "heading-存储提供商比较",
                "level": 3,
                "text": "存储提供商比较",
                "children": []
              }
            ]
          },
          {
            "id": "heading-安全考虑",
            "level": 2,
            "text": "安全考虑",
            "children": [
              {
                "id": "heading-S3-存储桶策略",
                "level": 3,
                "text": "S3 存储桶策略",
                "children": []
              },
              {
                "id": "heading-GitHub-仓库设置",
                "level": 3,
                "text": "GitHub 仓库设置",
                "children": []
              },
              {
                "id": "heading-环境变量",
                "level": 3,
                "text": "环境变量",
                "children": []
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "file": "usedb/postgresql.mdx",
    "path": "/usedb/postgresql",
    "title": "数据库申请",
    "toc": [
      {
        "id": "heading-免费PostgreSQL",
        "level": 1,
        "text": "免费PostgreSQL",
        "children": []
      }
    ]
  }
]

// Helper function to find TOC data by file path
export function getTocByFile(filePath: string): TocItem[] | undefined {
  const item = tocData.find(item => item.file === filePath)
  return item?.toc
}

// Helper function to find TOC data by route path
export function getTocByPath(routePath: string): TocItem[] | undefined {
  const item = tocData.find(item => item.path === routePath)
  return item?.toc
}

// Helper function to flatten TOC tree into a simple array
export function flattenToc(toc: TocItem[]): TocItem[] {
  const result: TocItem[] = []
  
  function traverse(items: TocItem[]) {
    for (const item of items) {
      result.push({
        id: item.id,
        level: item.level,
        text: item.text,
      })
      if (item.children && item.children.length > 0) {
        traverse(item.children)
      }
    }
  }
  
  traverse(toc)
  return result
}

// Helper function to get all headings at a specific level
export function getHeadingsByLevel(toc: TocItem[], level: number): TocItem[] {
  const result: TocItem[] = []
  
  function traverse(items: TocItem[]) {
    for (const item of items) {
      if (item.level === level) {
        result.push(item)
      }
      if (item.children && item.children.length > 0) {
        traverse(item.children)
      }
    }
  }
  
  traverse(toc)
  return result
}
